version: '3.4'

services:
  hostelpro:
    image: hostelpro
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
